#ifndef LOGINPLUGIN_GLOBAL_H
#define LOGINPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGINPLUGIN_LIBRARY)
#  define LOGINPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOGINPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGINPLUGIN_GLOBAL_H
