#ifndef SQUAREPLUGIN_GLOBAL_H
#define SQUAREPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQUAREPLUGIN_LIBRARY)
#  define SQUAREPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SQUAREPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SQUAREPLUGIN_GLOBAL_H
